# Excel connector test configuration
name: "Excel Connector Test"
description: "End-to-end test of Excel connector sync functionality with incremental deletion testing"

connector:
  name: "excel_test"
  type: "excel"
  auth_mode: composio
  composio_config:
    # Please ensure to add the following scopes to your Excel integration:
    # - Files.Read.All
    # - User.Read
    # - offline_access
    account_id: ca_GYtDsWRXFvk0
    auth_config_id: ac_OjD78XTDTWni
  config_fields:
    openai_model: "gpt-4.1-mini"

    # Timing: Allow Excel/OneDrive to index newly created workbooks
    # Excel needs time to propagate new files through OneDrive before they appear in listings
    post_create_sleep_seconds: 15

test_flow:
  steps:
    - cleanup
    - create
    - sync
    - verify
    - update
    - sync
    - verify
    - partial_delete
    - sync
    - verify_partial_deletion
    - verify_remaining_entities
    - complete_delete
    - sync
    - verify_complete_deletion
    - cleanup

# Entity configuration
entity_count: 3  # Number of worksheets to create for testing

deletion:
  # Phase 1: Partial deletion
  partial_delete_count: 1  # Number of worksheets to delete during partial deletion

  # Verification settings
  verify_partial_deletion: true  # Excel supports deletion detection
  verify_remaining_entities: true
  verify_complete_deletion: true

collection:
  name_template: "monke-{connector_type}-test-{timestamp}"
  description: "Test collection for {connector_type} connector"

verification:
  score_threshold: 0.1
  max_retries: 5  # Excel sync might take a bit longer
  retry_delay_seconds: 10  # Give Excel time to process

