# Google Sheets connector test configuration
name: "Google Sheets Connector Test"
description: "End-to-end test of Google Sheets connector sync functionality with incremental deletion testing"

connector:
  name: "google_sheets_test"
  type: "google_sheets"
  auth_mode: composio
  composio_config:
    # Please ensure to add the following scopes to your Google Sheets integration:
    # - https://www.googleapis.com/auth/spreadsheets (read and write spreadsheet content)
    # - https://www.googleapis.com/auth/drive.file (create and manage files created by the app)
    # - https://www.googleapis.com/auth/drive.readonly (read existing files for sync)
    account_id: ca_KBvJ2PkFrHiZ
    auth_config_id: ac_VAHbVAd8jTB6
  config_fields:
    openai_model: "gpt-4.1-mini"

    # Timing: Allow Google Drive to index newly created spreadsheets
    # Google Sheets needs time to propagate new files through Drive before they appear in listings
    post_create_sleep_seconds: 10

test_flow:
  steps:
    - cleanup
    - create
    - sync
    - verify
    - update
    - sync
    - verify
    - partial_delete
    - sync
    - verify_partial_deletion
    - verify_remaining_entities
    - complete_delete
    - sync
    - verify_complete_deletion
    - cleanup

# Entity configuration
entity_count: 3  # Number of spreadsheets to create for testing

deletion:
  # Phase 1: Partial deletion
  partial_delete_count: 1  # Number of spreadsheets to delete during partial deletion

  # Verification settings
  verify_partial_deletion: true  # Google Sheets supports deletion detection
  verify_remaining_entities: true
  verify_complete_deletion: true

collection:
  name_template: "monke-{connector_type}-test-{timestamp}"
  description: "Test collection for {connector_type} connector"

verification:
  score_threshold: 0.1
  max_retries: 5  # Google Sheets sync might take a bit longer
  retry_delay_seconds: 10  # Give Google time to process
