/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourceConnectionsIndexRouteImport } from './routes/source-connections/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsNewRouteImport } from './routes/collections/new'
import { Route as CollectionsSlugIndexRouteImport } from './routes/collections/$slug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceConnectionsIndexRoute = SourceConnectionsIndexRouteImport.update({
  id: '/source-connections/',
  path: '/source-connections/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsNewRoute = CollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugIndexRoute = CollectionsSlugIndexRouteImport.update({
  id: '/collections/$slug/',
  path: '/collections/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections/new': typeof CollectionsNewRoute
  '/collections': typeof CollectionsIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/source-connections': typeof SourceConnectionsIndexRoute
  '/collections/$slug': typeof CollectionsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections/new': typeof CollectionsNewRoute
  '/collections': typeof CollectionsIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/source-connections': typeof SourceConnectionsIndexRoute
  '/collections/$slug': typeof CollectionsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections/new': typeof CollectionsNewRoute
  '/collections/': typeof CollectionsIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/source-connections/': typeof SourceConnectionsIndexRoute
  '/collections/$slug/': typeof CollectionsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections/new'
    | '/collections'
    | '/components'
    | '/dashboard'
    | '/source-connections'
    | '/collections/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections/new'
    | '/collections'
    | '/components'
    | '/dashboard'
    | '/source-connections'
    | '/collections/$slug'
  id:
    | '__root__'
    | '/'
    | '/collections/new'
    | '/collections/'
    | '/components/'
    | '/dashboard/'
    | '/source-connections/'
    | '/collections/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsNewRoute: typeof CollectionsNewRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SourceConnectionsIndexRoute: typeof SourceConnectionsIndexRoute
  CollectionsSlugIndexRoute: typeof CollectionsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-connections/': {
      id: '/source-connections/'
      path: '/source-connections'
      fullPath: '/source-connections'
      preLoaderRoute: typeof SourceConnectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/new': {
      id: '/collections/new'
      path: '/collections/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof CollectionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug/': {
      id: '/collections/$slug/'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsNewRoute: CollectionsNewRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SourceConnectionsIndexRoute: SourceConnectionsIndexRoute,
  CollectionsSlugIndexRoute: CollectionsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
