import fs from "fs";
import path from "path";
import type { Plugin } from "vite";

export interface ComponentInfo {
  name: string;
  path: string;
  exports: string[];
}

function parseExports(filePath: string): string[] {
  const content = fs.readFileSync(filePath, "utf-8");
  const exports: string[] = [];

  // Match named exports: export { Name }, export { Name, Other }
  const namedExportMatch = content.match(/export\s*\{([^}]+)\}/g);
  if (namedExportMatch) {
    namedExportMatch.forEach((match) => {
      const names = match
        .replace(/export\s*\{/, "")
        .replace(/\}/, "")
        .split(",")
        .map((n) => n.trim().split(" as ")[0].trim())
        .filter(Boolean);
      exports.push(...names);
    });
  }

  // Match export function Name, export const Name, export class Name
  const directExportMatch = content.match(
    /export\s+(?:function|const|class|let|var)\s+(\w+)/g
  );
  if (directExportMatch) {
    directExportMatch.forEach((match) => {
      const name = match.replace(/export\s+(?:function|const|class|let|var)\s+/, "");
      if (name && !exports.includes(name)) {
        exports.push(name);
      }
    });
  }

  // Match export default (as "default")
  if (/export\s+default/.test(content)) {
    exports.push("default");
  }

  return exports;
}

function generateComponentsFile(uiDir: string, outputPath: string): void {
  if (!fs.existsSync(uiDir)) {
    fs.mkdirSync(uiDir, { recursive: true });
  }

  const files = fs.readdirSync(uiDir).filter((file) => {
    const ext = path.extname(file);
    return [".tsx", ".ts", ".jsx", ".js"].includes(ext) && !file.startsWith("_");
  });

  const components: ComponentInfo[] = files.map((file) => {
    const filePath = path.join(uiDir, file);
    const name = path.basename(file, path.extname(file));
    const exports = parseExports(filePath);

    return {
      name,
      path: `components/ui/${file}`,
      exports,
    };
  });

  const content = `/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by vite-plugin-components-gen.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter.

export interface ComponentInfo {
  name: string;
  path: string;
  exports: string[];
}

export const uiComponents: ComponentInfo[] = ${JSON.stringify(components, null, 2)};
`;

  fs.writeFileSync(outputPath, content, "utf-8");
}

export function componentsGen(): Plugin {
  let uiDir: string;
  let outputPath: string;

  return {
    name: "vite-plugin-components-gen",
    configResolved(config) {
      const srcDir = path.resolve(config.root, "src");
      uiDir = path.resolve(srcDir, "components/ui");
      outputPath = path.resolve(srcDir, "components.gen.ts");
    },
    buildStart() {
      generateComponentsFile(uiDir, outputPath);
    },
    configureServer(server) {
      // Watch for changes in the ui directory
      server.watcher.add(uiDir);
      
      server.watcher.on("add", (filePath) => {
        if (filePath.startsWith(uiDir) && !filePath.includes("components.gen")) {
          generateComponentsFile(uiDir, outputPath);
        }
      });

      server.watcher.on("unlink", (filePath) => {
        if (filePath.startsWith(uiDir) && !filePath.includes("components.gen")) {
          generateComponentsFile(uiDir, outputPath);
        }
      });

      server.watcher.on("change", (filePath) => {
        if (filePath.startsWith(uiDir) && !filePath.includes("components.gen")) {
          generateComponentsFile(uiDir, outputPath);
        }
      });
    },
  };
}

