/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by vite-plugin-components-gen.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter.

export interface ComponentInfo {
  name: string;
  path: string;
  exports: string[];
}

export const uiComponents: ComponentInfo[] = [
  {
    "name": "alert-dialog",
    "path": "components/ui/alert-dialog.tsx",
    "exports": [
      "AlertDialog",
      "AlertDialogPortal",
      "AlertDialogOverlay",
      "AlertDialogTrigger",
      "AlertDialogContent",
      "AlertDialogHeader",
      "AlertDialogFooter",
      "AlertDialogTitle",
      "AlertDialogDescription",
      "AlertDialogAction",
      "AlertDialogCancel"
    ]
  },
  {
    "name": "avatar",
    "path": "components/ui/avatar.tsx",
    "exports": [
      "Avatar",
      "AvatarImage",
      "AvatarFallback"
    ]
  },
  {
    "name": "badge",
    "path": "components/ui/badge.tsx",
    "exports": [
      "Badge",
      "badgeVariants"
    ]
  },
  {
    "name": "button",
    "path": "components/ui/button.tsx",
    "exports": [
      "Button",
      "buttonVariants"
    ]
  },
  {
    "name": "card",
    "path": "components/ui/card.tsx",
    "exports": [
      "Card",
      "CardHeader",
      "CardFooter",
      "CardTitle",
      "CardAction",
      "CardDescription",
      "CardContent"
    ]
  },
  {
    "name": "dialog",
    "path": "components/ui/dialog.tsx",
    "exports": [
      "Dialog",
      "DialogClose",
      "DialogContent",
      "DialogDescription",
      "DialogFooter",
      "DialogHeader",
      "DialogOverlay",
      "DialogPortal",
      "DialogTitle",
      "DialogTrigger"
    ]
  },
  {
    "name": "dropdown-menu",
    "path": "components/ui/dropdown-menu.tsx",
    "exports": [
      "DropdownMenu",
      "DropdownMenuPortal",
      "DropdownMenuTrigger",
      "DropdownMenuContent",
      "DropdownMenuGroup",
      "DropdownMenuLabel",
      "DropdownMenuItem",
      "DropdownMenuCheckboxItem",
      "DropdownMenuRadioGroup",
      "DropdownMenuRadioItem",
      "DropdownMenuSeparator",
      "DropdownMenuShortcut",
      "DropdownMenuSub",
      "DropdownMenuSubTrigger",
      "DropdownMenuSubContent"
    ]
  },
  {
    "name": "input",
    "path": "components/ui/input.tsx",
    "exports": [
      "Input"
    ]
  },
  {
    "name": "right-sidebar",
    "path": "components/ui/right-sidebar.tsx",
    "exports": [
      "RightSidebarProvider",
      "RightSidebarTabs",
      "RightSidebarPanel",
      "RightSidebarTrigger",
      "MobileBottomNav",
      "MobileRightSidebarSheet",
      "useRightSidebar",
      "useRightSidebarContent",
      "type TabId",
      "type RightSidebarContent"
    ]
  },
  {
    "name": "separator",
    "path": "components/ui/separator.tsx",
    "exports": [
      "Separator"
    ]
  },
  {
    "name": "sheet",
    "path": "components/ui/sheet.tsx",
    "exports": [
      "Sheet",
      "SheetTrigger",
      "SheetClose",
      "SheetContent",
      "SheetHeader",
      "SheetFooter",
      "SheetTitle",
      "SheetDescription"
    ]
  },
  {
    "name": "sidebar",
    "path": "components/ui/sidebar.tsx",
    "exports": [
      "Sidebar",
      "SidebarContent",
      "SidebarFooter",
      "SidebarGroup",
      "SidebarGroupAction",
      "SidebarGroupContent",
      "SidebarGroupLabel",
      "SidebarHeader",
      "SidebarInput",
      "SidebarInset",
      "SidebarMenu",
      "SidebarMenuAction",
      "SidebarMenuBadge",
      "SidebarMenuButton",
      "SidebarMenuItem",
      "SidebarMenuSkeleton",
      "SidebarMenuSub",
      "SidebarMenuSubButton",
      "SidebarMenuSubItem",
      "SidebarProvider",
      "SidebarRail",
      "SidebarSeparator",
      "SidebarTrigger",
      "useSidebar"
    ]
  },
  {
    "name": "skeleton",
    "path": "components/ui/skeleton.tsx",
    "exports": [
      "Skeleton"
    ]
  },
  {
    "name": "tooltip",
    "path": "components/ui/tooltip.tsx",
    "exports": [
      "Tooltip",
      "TooltipTrigger",
      "TooltipContent",
      "TooltipProvider"
    ]
  }
];
