/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by vite-plugin-components-gen.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter.

export interface ComponentInfo {
  name: string;
  path: string;
  exports: string[];
}

export const uiComponents: ComponentInfo[] = [
  {
    "name": "alert-dialog",
    "path": "components/ui/alert-dialog.tsx",
    "exports": [
      "AlertDialog",
      "AlertDialogPortal",
      "AlertDialogOverlay",
      "AlertDialogTrigger",
      "AlertDialogContent",
      "AlertDialogHeader",
      "AlertDialogFooter",
      "AlertDialogTitle",
      "AlertDialogDescription",
      "AlertDialogAction",
      "AlertDialogCancel"
    ]
  },
  {
    "name": "button",
    "path": "components/ui/button.tsx",
    "exports": [
      "Button",
      "buttonVariants"
    ]
  }
];
