/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by vite-plugin-components-gen.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter.

export interface ComponentInfo {
  name: string;
  path: string;
  exports: string[];
}

export const uiComponents: ComponentInfo[] = [
  {
    "name": "alert-dialog",
    "path": "components/ui/alert-dialog.tsx",
    "exports": [
      "AlertDialog",
      "AlertDialogAction",
      "AlertDialogCancel",
      "AlertDialogContent",
      "AlertDialogDescription",
      "AlertDialogFooter",
      "AlertDialogHeader",
      "AlertDialogOverlay",
      "AlertDialogPortal",
      "AlertDialogTitle",
      "AlertDialogTrigger"
    ]
  },
  {
    "name": "alert",
    "path": "components/ui/alert.tsx",
    "exports": [
      "Alert",
      "AlertTitle",
      "AlertDescription"
    ]
  },
  {
    "name": "api-form",
    "path": "components/ui/api-form.tsx",
    "exports": [
      "ApiForm"
    ]
  },
  {
    "name": "avatar",
    "path": "components/ui/avatar.tsx",
    "exports": [
      "Avatar",
      "AvatarImage",
      "AvatarFallback"
    ]
  },
  {
    "name": "badge",
    "path": "components/ui/badge.tsx",
    "exports": [
      "Badge",
      "badgeVariants"
    ]
  },
  {
    "name": "button",
    "path": "components/ui/button.tsx",
    "exports": [
      "Button",
      "buttonVariants"
    ]
  },
  {
    "name": "card",
    "path": "components/ui/card.tsx",
    "exports": [
      "Card",
      "CardHeader",
      "CardFooter",
      "CardTitle",
      "CardAction",
      "CardDescription",
      "CardContent"
    ]
  },
  {
    "name": "checkbox",
    "path": "components/ui/checkbox.tsx",
    "exports": [
      "Checkbox"
    ]
  },
  {
    "name": "command",
    "path": "components/ui/command.tsx",
    "exports": [
      "Command",
      "CommandDialog",
      "CommandInput",
      "CommandList",
      "CommandEmpty",
      "CommandGroup",
      "CommandItem",
      "CommandShortcut",
      "CommandSeparator"
    ]
  },
  {
    "name": "delete-confirmation-dialog",
    "path": "components/ui/delete-confirmation-dialog.tsx",
    "exports": [
      "DeleteConfirmationDialog"
    ]
  },
  {
    "name": "dialog",
    "path": "components/ui/dialog.tsx",
    "exports": [
      "Dialog",
      "DialogClose",
      "DialogContent",
      "DialogDescription",
      "DialogFooter",
      "DialogHeader",
      "DialogOverlay",
      "DialogPortal",
      "DialogTitle",
      "DialogTrigger"
    ]
  },
  {
    "name": "discord-icon",
    "path": "components/ui/discord-icon.tsx",
    "exports": [
      "DiscordIcon"
    ]
  },
  {
    "name": "dropdown-menu",
    "path": "components/ui/dropdown-menu.tsx",
    "exports": [
      "DropdownMenu",
      "DropdownMenuCheckboxItem",
      "DropdownMenuContent",
      "DropdownMenuGroup",
      "DropdownMenuItem",
      "DropdownMenuLabel",
      "DropdownMenuPortal",
      "DropdownMenuRadioGroup",
      "DropdownMenuRadioItem",
      "DropdownMenuSeparator",
      "DropdownMenuShortcut",
      "DropdownMenuSub",
      "DropdownMenuSubContent",
      "DropdownMenuSubTrigger",
      "DropdownMenuTrigger"
    ]
  },
  {
    "name": "empty-state",
    "path": "components/ui/empty-state.tsx",
    "exports": [
      "EmptyState",
      "type EmptyStateProps"
    ]
  },
  {
    "name": "error-state",
    "path": "components/ui/error-state.tsx",
    "exports": [
      "ErrorState"
    ]
  },
  {
    "name": "input",
    "path": "components/ui/input.tsx",
    "exports": [
      "Input"
    ]
  },
  {
    "name": "label",
    "path": "components/ui/label.tsx",
    "exports": [
      "Label"
    ]
  },
  {
    "name": "loading-state",
    "path": "components/ui/loading-state.tsx",
    "exports": [
      "LoadingState"
    ]
  },
  {
    "name": "page-header",
    "path": "components/ui/page-header.tsx",
    "exports": [
      "PageHeaderContent",
      "PageHeaderProvider",
      "usePageHeader",
      "usePageHeaderContext",
      "type PageHeaderContent"
    ]
  },
  {
    "name": "right-sidebar",
    "path": "components/ui/right-sidebar.tsx",
    "exports": [
      "MobileBottomNav",
      "MobileRightSidebarSheet",
      "RightSidebarPanel",
      "RightSidebarProvider",
      "RightSidebarTabs",
      "RightSidebarTrigger",
      "useRightSidebar",
      "useRightSidebarContent",
      "type RightSidebarContent",
      "type TabId"
    ]
  },
  {
    "name": "select",
    "path": "components/ui/select.tsx",
    "exports": [
      "Select",
      "SelectGroup",
      "SelectValue",
      "SelectTrigger",
      "SelectContent",
      "SelectLabel",
      "SelectItem",
      "SelectSeparator"
    ]
  },
  {
    "name": "separator",
    "path": "components/ui/separator.tsx",
    "exports": [
      "Separator"
    ]
  },
  {
    "name": "sheet",
    "path": "components/ui/sheet.tsx",
    "exports": [
      "Sheet",
      "SheetTrigger",
      "SheetClose",
      "SheetContent",
      "SheetHeader",
      "SheetFooter",
      "SheetTitle",
      "SheetDescription"
    ]
  },
  {
    "name": "sidebar",
    "path": "components/ui/sidebar.tsx",
    "exports": [
      "Sidebar",
      "SidebarContent",
      "SidebarFooter",
      "SidebarGroup",
      "SidebarGroupAction",
      "SidebarGroupContent",
      "SidebarGroupLabel",
      "SidebarHeader",
      "SidebarInput",
      "SidebarInset",
      "SidebarMenu",
      "SidebarMenuAction",
      "SidebarMenuBadge",
      "SidebarMenuButton",
      "SidebarMenuItem",
      "SidebarMenuSkeleton",
      "SidebarMenuSub",
      "SidebarMenuSubButton",
      "SidebarMenuSubItem",
      "SidebarProvider",
      "SidebarRail",
      "SidebarSeparator",
      "SidebarTrigger",
      "useSidebar"
    ]
  },
  {
    "name": "skeleton",
    "path": "components/ui/skeleton.tsx",
    "exports": [
      "Skeleton"
    ]
  },
  {
    "name": "sonner",
    "path": "components/ui/sonner.tsx",
    "exports": [
      "Toaster"
    ]
  },
  {
    "name": "steps",
    "path": "components/ui/steps.tsx",
    "exports": [
      "useStepsContext",
      "Steps"
    ]
  },
  {
    "name": "switch",
    "path": "components/ui/switch.tsx",
    "exports": [
      "Switch"
    ]
  },
  {
    "name": "table",
    "path": "components/ui/table.tsx",
    "exports": [
      "Table",
      "TableBody",
      "TableCaption",
      "TableCell",
      "TableFooter",
      "TableHead",
      "TableHeader",
      "TableRow"
    ]
  },
  {
    "name": "tabs",
    "path": "components/ui/tabs.tsx",
    "exports": [
      "Tabs",
      "TabsList",
      "TabsTrigger",
      "TabsContent"
    ]
  },
  {
    "name": "textarea",
    "path": "components/ui/textarea.tsx",
    "exports": [
      "Textarea"
    ]
  },
  {
    "name": "tooltip",
    "path": "components/ui/tooltip.tsx",
    "exports": [
      "Tooltip",
      "TooltipTrigger",
      "TooltipContent",
      "TooltipProvider"
    ]
  }
];
