/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemanticMcpRouteImport } from './routes/semantic-mcp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OrgSlugRouteRouteImport } from './routes/$orgSlug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as ComponentsComponentNameRouteImport } from './routes/components.$componentName'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as BillingSetupRouteImport } from './routes/billing/setup'
import { Route as BillingPortalRouteImport } from './routes/billing/portal'
import { Route as BillingCancelRouteImport } from './routes/billing/cancel'
import { Route as OrgSlugWebhooksRouteImport } from './routes/$orgSlug/webhooks'
import { Route as OrgSlugLogsRouteImport } from './routes/$orgSlug/logs'
import { Route as OrgSlugAuthProvidersRouteImport } from './routes/$orgSlug/auth-providers'
import { Route as OrgSlugApiKeysRouteImport } from './routes/$orgSlug/api-keys'
import { Route as OrgSlugSettingsIndexRouteImport } from './routes/$orgSlug/settings/index'
import { Route as OrgSlugCollectionsIndexRouteImport } from './routes/$orgSlug/collections/index'
import { Route as OrgSlugSettingsUsageRouteImport } from './routes/$orgSlug/settings/usage'
import { Route as OrgSlugSettingsMembersRouteImport } from './routes/$orgSlug/settings/members'
import { Route as OrgSlugSettingsBillingRouteImport } from './routes/$orgSlug/settings/billing'
import { Route as OrgSlugCollectionsCollectionIdRouteImport } from './routes/$orgSlug/collections/$collectionId'

const SemanticMcpRoute = SemanticMcpRouteImport.update({
  id: '/semantic-mcp',
  path: '/semantic-mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRoute,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const ComponentsComponentNameRoute = ComponentsComponentNameRouteImport.update({
  id: '/$componentName',
  path: '/$componentName',
  getParentRoute: () => ComponentsRoute,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSetupRoute = BillingSetupRouteImport.update({
  id: '/billing/setup',
  path: '/billing/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPortalRoute = BillingPortalRouteImport.update({
  id: '/billing/portal',
  path: '/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/billing/cancel',
  path: '/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugWebhooksRoute = OrgSlugWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugLogsRoute = OrgSlugLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugAuthProvidersRoute = OrgSlugAuthProvidersRouteImport.update({
  id: '/auth-providers',
  path: '/auth-providers',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugApiKeysRoute = OrgSlugApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugCollectionsIndexRoute = OrgSlugCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugSettingsUsageRoute = OrgSlugSettingsUsageRouteImport.update({
  id: '/settings/usage',
  path: '/settings/usage',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugSettingsMembersRoute = OrgSlugSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugSettingsBillingRoute = OrgSlugSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugCollectionsCollectionIdRoute =
  OrgSlugCollectionsCollectionIdRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/components': typeof ComponentsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/semantic-mcp': typeof SemanticMcpRoute
  '/$orgSlug/api-keys': typeof OrgSlugApiKeysRoute
  '/$orgSlug/auth-providers': typeof OrgSlugAuthProvidersRoute
  '/$orgSlug/logs': typeof OrgSlugLogsRoute
  '/$orgSlug/webhooks': typeof OrgSlugWebhooksRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/portal': typeof BillingPortalRoute
  '/billing/setup': typeof BillingSetupRoute
  '/billing/success': typeof BillingSuccessRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/$orgSlug/collections/$collectionId': typeof OrgSlugCollectionsCollectionIdRoute
  '/$orgSlug/settings/billing': typeof OrgSlugSettingsBillingRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/usage': typeof OrgSlugSettingsUsageRoute
  '/$orgSlug/collections': typeof OrgSlugCollectionsIndexRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/onboarding': typeof OnboardingRoute
  '/semantic-mcp': typeof SemanticMcpRoute
  '/$orgSlug/api-keys': typeof OrgSlugApiKeysRoute
  '/$orgSlug/auth-providers': typeof OrgSlugAuthProvidersRoute
  '/$orgSlug/logs': typeof OrgSlugLogsRoute
  '/$orgSlug/webhooks': typeof OrgSlugWebhooksRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/portal': typeof BillingPortalRoute
  '/billing/setup': typeof BillingSetupRoute
  '/billing/success': typeof BillingSuccessRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/$orgSlug/collections/$collectionId': typeof OrgSlugCollectionsCollectionIdRoute
  '/$orgSlug/settings/billing': typeof OrgSlugSettingsBillingRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/usage': typeof OrgSlugSettingsUsageRoute
  '/$orgSlug/collections': typeof OrgSlugCollectionsIndexRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/components': typeof ComponentsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/semantic-mcp': typeof SemanticMcpRoute
  '/$orgSlug/api-keys': typeof OrgSlugApiKeysRoute
  '/$orgSlug/auth-providers': typeof OrgSlugAuthProvidersRoute
  '/$orgSlug/logs': typeof OrgSlugLogsRoute
  '/$orgSlug/webhooks': typeof OrgSlugWebhooksRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/portal': typeof BillingPortalRoute
  '/billing/setup': typeof BillingSetupRoute
  '/billing/success': typeof BillingSuccessRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/$orgSlug/collections/$collectionId': typeof OrgSlugCollectionsCollectionIdRoute
  '/$orgSlug/settings/billing': typeof OrgSlugSettingsBillingRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/usage': typeof OrgSlugSettingsUsageRoute
  '/$orgSlug/collections/': typeof OrgSlugCollectionsIndexRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/components'
    | '/onboarding'
    | '/semantic-mcp'
    | '/$orgSlug/api-keys'
    | '/$orgSlug/auth-providers'
    | '/$orgSlug/logs'
    | '/$orgSlug/webhooks'
    | '/billing/cancel'
    | '/billing/portal'
    | '/billing/setup'
    | '/billing/success'
    | '/components/$componentName'
    | '/$orgSlug/'
    | '/components/'
    | '/$orgSlug/collections/$collectionId'
    | '/$orgSlug/settings/billing'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/usage'
    | '/$orgSlug/collections'
    | '/$orgSlug/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/onboarding'
    | '/semantic-mcp'
    | '/$orgSlug/api-keys'
    | '/$orgSlug/auth-providers'
    | '/$orgSlug/logs'
    | '/$orgSlug/webhooks'
    | '/billing/cancel'
    | '/billing/portal'
    | '/billing/setup'
    | '/billing/success'
    | '/components/$componentName'
    | '/$orgSlug'
    | '/components'
    | '/$orgSlug/collections/$collectionId'
    | '/$orgSlug/settings/billing'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/usage'
    | '/$orgSlug/collections'
    | '/$orgSlug/settings'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/components'
    | '/onboarding'
    | '/semantic-mcp'
    | '/$orgSlug/api-keys'
    | '/$orgSlug/auth-providers'
    | '/$orgSlug/logs'
    | '/$orgSlug/webhooks'
    | '/billing/cancel'
    | '/billing/portal'
    | '/billing/setup'
    | '/billing/success'
    | '/components/$componentName'
    | '/$orgSlug/'
    | '/components/'
    | '/$orgSlug/collections/$collectionId'
    | '/$orgSlug/settings/billing'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/usage'
    | '/$orgSlug/collections/'
    | '/$orgSlug/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SemanticMcpRoute: typeof SemanticMcpRoute
  BillingCancelRoute: typeof BillingCancelRoute
  BillingPortalRoute: typeof BillingPortalRoute
  BillingSetupRoute: typeof BillingSetupRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/semantic-mcp': {
      id: '/semantic-mcp'
      path: '/semantic-mcp'
      fullPath: '/semantic-mcp'
      preLoaderRoute: typeof SemanticMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/components/$componentName': {
      id: '/components/$componentName'
      path: '/$componentName'
      fullPath: '/components/$componentName'
      preLoaderRoute: typeof ComponentsComponentNameRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/setup': {
      id: '/billing/setup'
      path: '/billing/setup'
      fullPath: '/billing/setup'
      preLoaderRoute: typeof BillingSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/portal': {
      id: '/billing/portal'
      path: '/billing/portal'
      fullPath: '/billing/portal'
      preLoaderRoute: typeof BillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/billing/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/webhooks': {
      id: '/$orgSlug/webhooks'
      path: '/webhooks'
      fullPath: '/$orgSlug/webhooks'
      preLoaderRoute: typeof OrgSlugWebhooksRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/logs': {
      id: '/$orgSlug/logs'
      path: '/logs'
      fullPath: '/$orgSlug/logs'
      preLoaderRoute: typeof OrgSlugLogsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/auth-providers': {
      id: '/$orgSlug/auth-providers'
      path: '/auth-providers'
      fullPath: '/$orgSlug/auth-providers'
      preLoaderRoute: typeof OrgSlugAuthProvidersRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/api-keys': {
      id: '/$orgSlug/api-keys'
      path: '/api-keys'
      fullPath: '/$orgSlug/api-keys'
      preLoaderRoute: typeof OrgSlugApiKeysRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/settings/': {
      id: '/$orgSlug/settings/'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/collections/': {
      id: '/$orgSlug/collections/'
      path: '/collections'
      fullPath: '/$orgSlug/collections'
      preLoaderRoute: typeof OrgSlugCollectionsIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/settings/usage': {
      id: '/$orgSlug/settings/usage'
      path: '/settings/usage'
      fullPath: '/$orgSlug/settings/usage'
      preLoaderRoute: typeof OrgSlugSettingsUsageRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/settings/members': {
      id: '/$orgSlug/settings/members'
      path: '/settings/members'
      fullPath: '/$orgSlug/settings/members'
      preLoaderRoute: typeof OrgSlugSettingsMembersRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/settings/billing': {
      id: '/$orgSlug/settings/billing'
      path: '/settings/billing'
      fullPath: '/$orgSlug/settings/billing'
      preLoaderRoute: typeof OrgSlugSettingsBillingRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/collections/$collectionId': {
      id: '/$orgSlug/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/$orgSlug/collections/$collectionId'
      preLoaderRoute: typeof OrgSlugCollectionsCollectionIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
  }
}

interface OrgSlugRouteRouteChildren {
  OrgSlugApiKeysRoute: typeof OrgSlugApiKeysRoute
  OrgSlugAuthProvidersRoute: typeof OrgSlugAuthProvidersRoute
  OrgSlugLogsRoute: typeof OrgSlugLogsRoute
  OrgSlugWebhooksRoute: typeof OrgSlugWebhooksRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugCollectionsCollectionIdRoute: typeof OrgSlugCollectionsCollectionIdRoute
  OrgSlugSettingsBillingRoute: typeof OrgSlugSettingsBillingRoute
  OrgSlugSettingsMembersRoute: typeof OrgSlugSettingsMembersRoute
  OrgSlugSettingsUsageRoute: typeof OrgSlugSettingsUsageRoute
  OrgSlugCollectionsIndexRoute: typeof OrgSlugCollectionsIndexRoute
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugApiKeysRoute: OrgSlugApiKeysRoute,
  OrgSlugAuthProvidersRoute: OrgSlugAuthProvidersRoute,
  OrgSlugLogsRoute: OrgSlugLogsRoute,
  OrgSlugWebhooksRoute: OrgSlugWebhooksRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugCollectionsCollectionIdRoute: OrgSlugCollectionsCollectionIdRoute,
  OrgSlugSettingsBillingRoute: OrgSlugSettingsBillingRoute,
  OrgSlugSettingsMembersRoute: OrgSlugSettingsMembersRoute,
  OrgSlugSettingsUsageRoute: OrgSlugSettingsUsageRoute,
  OrgSlugCollectionsIndexRoute: OrgSlugCollectionsIndexRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
}

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
)

interface ComponentsRouteChildren {
  ComponentsComponentNameRoute: typeof ComponentsComponentNameRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsComponentNameRoute: ComponentsComponentNameRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SemanticMcpRoute: SemanticMcpRoute,
  BillingCancelRoute: BillingCancelRoute,
  BillingPortalRoute: BillingPortalRoute,
  BillingSetupRoute: BillingSetupRoute,
  BillingSuccessRoute: BillingSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
