/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AuthProvidersRouteImport } from './routes/auth-providers'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as ApiKeysIndexRouteImport } from './routes/api-keys/index'
import { Route as ComponentsComponentNameRouteImport } from './routes/components.$componentName'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProvidersRoute = AuthProvidersRouteImport.update({
  id: '/auth-providers',
  path: '/auth-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRoute,
} as any)
const ApiKeysIndexRoute = ApiKeysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiKeysRoute,
} as any)
const ComponentsComponentNameRoute = ComponentsComponentNameRouteImport.update({
  id: '/$componentName',
  path: '/$componentName',
  getParentRoute: () => ComponentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRouteWithChildren
  '/auth-providers': typeof AuthProvidersRoute
  '/collections': typeof CollectionsRoute
  '/components': typeof ComponentsRouteWithChildren
  '/logs': typeof LogsRoute
  '/webhooks': typeof WebhooksRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/api-keys/': typeof ApiKeysIndexRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-providers': typeof AuthProvidersRoute
  '/collections': typeof CollectionsRoute
  '/logs': typeof LogsRoute
  '/webhooks': typeof WebhooksRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/api-keys': typeof ApiKeysIndexRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRouteWithChildren
  '/auth-providers': typeof AuthProvidersRoute
  '/collections': typeof CollectionsRoute
  '/components': typeof ComponentsRouteWithChildren
  '/logs': typeof LogsRoute
  '/webhooks': typeof WebhooksRoute
  '/components/$componentName': typeof ComponentsComponentNameRoute
  '/api-keys/': typeof ApiKeysIndexRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/auth-providers'
    | '/collections'
    | '/components'
    | '/logs'
    | '/webhooks'
    | '/components/$componentName'
    | '/api-keys/'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-providers'
    | '/collections'
    | '/logs'
    | '/webhooks'
    | '/components/$componentName'
    | '/api-keys'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/auth-providers'
    | '/collections'
    | '/components'
    | '/logs'
    | '/webhooks'
    | '/components/$componentName'
    | '/api-keys/'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRouteWithChildren
  AuthProvidersRoute: typeof AuthProvidersRoute
  CollectionsRoute: typeof CollectionsRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
  LogsRoute: typeof LogsRoute
  WebhooksRoute: typeof WebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-providers': {
      id: '/auth-providers'
      path: '/auth-providers'
      fullPath: '/auth-providers'
      preLoaderRoute: typeof AuthProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/api-keys/': {
      id: '/api-keys/'
      path: '/'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof ApiKeysIndexRouteImport
      parentRoute: typeof ApiKeysRoute
    }
    '/components/$componentName': {
      id: '/components/$componentName'
      path: '/$componentName'
      fullPath: '/components/$componentName'
      preLoaderRoute: typeof ComponentsComponentNameRouteImport
      parentRoute: typeof ComponentsRoute
    }
  }
}

interface ApiKeysRouteChildren {
  ApiKeysIndexRoute: typeof ApiKeysIndexRoute
}

const ApiKeysRouteChildren: ApiKeysRouteChildren = {
  ApiKeysIndexRoute: ApiKeysIndexRoute,
}

const ApiKeysRouteWithChildren =
  ApiKeysRoute._addFileChildren(ApiKeysRouteChildren)

interface ComponentsRouteChildren {
  ComponentsComponentNameRoute: typeof ComponentsComponentNameRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsComponentNameRoute: ComponentsComponentNameRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRouteWithChildren,
  AuthProvidersRoute: AuthProvidersRoute,
  CollectionsRoute: CollectionsRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
  LogsRoute: LogsRoute,
  WebhooksRoute: WebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
