import type { ReactNode } from "react";
import { HeadContent, Scripts, createRootRoute } from "@tanstack/react-router";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { createHead, UnheadProvider } from "@unhead/react/client";
import { SessionProvider } from "../components/SessionProvider";
import appCss from "../styles.css?url";

const head = createHead();

const queryClient = new QueryClient();

export const Route = createRootRoute({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
      {
        title: "Airweave Connect",
      },
    ],
    links: [
      {
        rel: "stylesheet",
        href: appCss,
      },
    ],
    scripts: [
      {
        // Runtime config injection for Docker deployments
        // This script is generated by docker-entrypoint.sh and sets window.__CONNECT_ENV__
        src: "/config.js",
      },
    ],
  }),

  shellComponent: RootDocument,
});

function RootDocument({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body style={{ backgroundColor: "var(--connect-bg, transparent)" }}>
        <UnheadProvider head={head}>
          <QueryClientProvider client={queryClient}>
            <SessionProvider />
            {children}
          </QueryClientProvider>
        </UnheadProvider>
        <Scripts />
      </body>
    </html>
  );
}
