/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as CallbackRouteImport } from './routes/callback';
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route';
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding';
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route';
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index';
import { Route as AuthenticatedAppAuthProvidersRouteImport } from './routes/_authenticated/_app/auth-providers';
import { Route as AuthenticatedAppApiKeysRouteImport } from './routes/_authenticated/_app/api-keys';
import { Route as AuthenticatedAppCollectionsIndexRouteImport } from './routes/_authenticated/_app/collections/index';
import { Route as AuthenticatedAppCollectionsCollectionIdRouteImport } from './routes/_authenticated/_app/collections/$collectionId';
import { Route as AuthenticatedAppApiKeysCreateRouteImport } from './routes/_authenticated/_app/api-keys.create';
import { Route as AuthenticatedAppCollectionsCollectionIdConnectSourceRouteImport } from './routes/_authenticated/_app/collections/$collectionId.connect-source';
import { Route as AuthenticatedAppAuthProvidersShortNameConnectRouteImport } from './routes/_authenticated/_app/auth-providers.$shortName.connect';
import { Route as AuthenticatedAppCollectionsCollectionIdConnectSourceIndexRouteImport } from './routes/_authenticated/_app/collections/$collectionId.connect-source.index';
import { Route as AuthenticatedAppAuthProvidersConnectionsReadableIdEditRouteImport } from './routes/_authenticated/_app/auth-providers.connections.$readableId.edit';
import { Route as AuthenticatedAppAuthProvidersConnectionsReadableIdDeleteRouteImport } from './routes/_authenticated/_app/auth-providers.connections.$readableId.delete';
import { Route as AuthenticatedAppCollectionsCollectionIdConnectSourceSourceSyncRouteImport } from './routes/_authenticated/_app/collections/$collectionId.connect-source.$source.sync';
import { Route as AuthenticatedAppCollectionsCollectionIdConnectSourceSourceConfigRouteImport } from './routes/_authenticated/_app/collections/$collectionId.connect-source.$source.config';
import { Route as AuthenticatedAppCollectionsCollectionIdConnectSourceSourceAuthRouteImport } from './routes/_authenticated/_app/collections/$collectionId.connect-source.$source.auth';

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any);
const AuthenticatedAppAuthProvidersRoute =
  AuthenticatedAppAuthProvidersRouteImport.update({
    id: '/auth-providers',
    path: '/auth-providers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any);
const AuthenticatedAppApiKeysRoute = AuthenticatedAppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any);
const AuthenticatedAppCollectionsIndexRoute =
  AuthenticatedAppCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any);
const AuthenticatedAppCollectionsCollectionIdRoute =
  AuthenticatedAppCollectionsCollectionIdRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any);
const AuthenticatedAppApiKeysCreateRoute =
  AuthenticatedAppApiKeysCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAppApiKeysRoute,
  } as any);
const AuthenticatedAppCollectionsCollectionIdConnectSourceRoute =
  AuthenticatedAppCollectionsCollectionIdConnectSourceRouteImport.update({
    id: '/connect-source',
    path: '/connect-source',
    getParentRoute: () => AuthenticatedAppCollectionsCollectionIdRoute,
  } as any);
const AuthenticatedAppAuthProvidersShortNameConnectRoute =
  AuthenticatedAppAuthProvidersShortNameConnectRouteImport.update({
    id: '/$shortName/connect',
    path: '/$shortName/connect',
    getParentRoute: () => AuthenticatedAppAuthProvidersRoute,
  } as any);
const AuthenticatedAppCollectionsCollectionIdConnectSourceIndexRoute =
  AuthenticatedAppCollectionsCollectionIdConnectSourceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedAppCollectionsCollectionIdConnectSourceRoute,
  } as any);
const AuthenticatedAppAuthProvidersConnectionsReadableIdEditRoute =
  AuthenticatedAppAuthProvidersConnectionsReadableIdEditRouteImport.update({
    id: '/connections/$readableId/edit',
    path: '/connections/$readableId/edit',
    getParentRoute: () => AuthenticatedAppAuthProvidersRoute,
  } as any);
const AuthenticatedAppAuthProvidersConnectionsReadableIdDeleteRoute =
  AuthenticatedAppAuthProvidersConnectionsReadableIdDeleteRouteImport.update({
    id: '/connections/$readableId/delete',
    path: '/connections/$readableId/delete',
    getParentRoute: () => AuthenticatedAppAuthProvidersRoute,
  } as any);
const AuthenticatedAppCollectionsCollectionIdConnectSourceSourceSyncRoute =
  AuthenticatedAppCollectionsCollectionIdConnectSourceSourceSyncRouteImport.update(
    {
      id: '/$source/sync',
      path: '/$source/sync',
      getParentRoute: () =>
        AuthenticatedAppCollectionsCollectionIdConnectSourceRoute,
    } as any,
  );
const AuthenticatedAppCollectionsCollectionIdConnectSourceSourceConfigRoute =
  AuthenticatedAppCollectionsCollectionIdConnectSourceSourceConfigRouteImport.update(
    {
      id: '/$source/config',
      path: '/$source/config',
      getParentRoute: () =>
        AuthenticatedAppCollectionsCollectionIdConnectSourceRoute,
    } as any,
  );
const AuthenticatedAppCollectionsCollectionIdConnectSourceSourceAuthRoute =
  AuthenticatedAppCollectionsCollectionIdConnectSourceSourceAuthRouteImport.update(
    {
      id: '/$source/auth',
      path: '/$source/auth',
      getParentRoute: () =>
        AuthenticatedAppCollectionsCollectionIdConnectSourceRoute,
    } as any,
  );

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute;
  '/callback': typeof CallbackRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof AuthenticatedOnboardingRoute;
  '/api-keys': typeof AuthenticatedAppApiKeysRouteWithChildren;
  '/auth-providers': typeof AuthenticatedAppAuthProvidersRouteWithChildren;
  '/api-keys/create': typeof AuthenticatedAppApiKeysCreateRoute;
  '/collections/$collectionId': typeof AuthenticatedAppCollectionsCollectionIdRouteWithChildren;
  '/collections/': typeof AuthenticatedAppCollectionsIndexRoute;
  '/auth-providers/$shortName/connect': typeof AuthenticatedAppAuthProvidersShortNameConnectRoute;
  '/collections/$collectionId/connect-source': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceRouteWithChildren;
  '/auth-providers/connections/$readableId/delete': typeof AuthenticatedAppAuthProvidersConnectionsReadableIdDeleteRoute;
  '/auth-providers/connections/$readableId/edit': typeof AuthenticatedAppAuthProvidersConnectionsReadableIdEditRoute;
  '/collections/$collectionId/connect-source/': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceIndexRoute;
  '/collections/$collectionId/connect-source/$source/auth': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceAuthRoute;
  '/collections/$collectionId/connect-source/$source/config': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceConfigRoute;
  '/collections/$collectionId/connect-source/$source/sync': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceSyncRoute;
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute;
  '/callback': typeof CallbackRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof AuthenticatedOnboardingRoute;
  '/api-keys': typeof AuthenticatedAppApiKeysRouteWithChildren;
  '/auth-providers': typeof AuthenticatedAppAuthProvidersRouteWithChildren;
  '/api-keys/create': typeof AuthenticatedAppApiKeysCreateRoute;
  '/collections/$collectionId': typeof AuthenticatedAppCollectionsCollectionIdRouteWithChildren;
  '/collections': typeof AuthenticatedAppCollectionsIndexRoute;
  '/auth-providers/$shortName/connect': typeof AuthenticatedAppAuthProvidersShortNameConnectRoute;
  '/auth-providers/connections/$readableId/delete': typeof AuthenticatedAppAuthProvidersConnectionsReadableIdDeleteRoute;
  '/auth-providers/connections/$readableId/edit': typeof AuthenticatedAppAuthProvidersConnectionsReadableIdEditRoute;
  '/collections/$collectionId/connect-source': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceIndexRoute;
  '/collections/$collectionId/connect-source/$source/auth': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceAuthRoute;
  '/collections/$collectionId/connect-source/$source/config': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceConfigRoute;
  '/collections/$collectionId/connect-source/$source/sync': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceSyncRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren;
  '/callback': typeof CallbackRoute;
  '/login': typeof LoginRoute;
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren;
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute;
  '/_authenticated/_app/api-keys': typeof AuthenticatedAppApiKeysRouteWithChildren;
  '/_authenticated/_app/auth-providers': typeof AuthenticatedAppAuthProvidersRouteWithChildren;
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute;
  '/_authenticated/_app/api-keys/create': typeof AuthenticatedAppApiKeysCreateRoute;
  '/_authenticated/_app/collections/$collectionId': typeof AuthenticatedAppCollectionsCollectionIdRouteWithChildren;
  '/_authenticated/_app/collections/': typeof AuthenticatedAppCollectionsIndexRoute;
  '/_authenticated/_app/auth-providers/$shortName/connect': typeof AuthenticatedAppAuthProvidersShortNameConnectRoute;
  '/_authenticated/_app/collections/$collectionId/connect-source': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceRouteWithChildren;
  '/_authenticated/_app/auth-providers/connections/$readableId/delete': typeof AuthenticatedAppAuthProvidersConnectionsReadableIdDeleteRoute;
  '/_authenticated/_app/auth-providers/connections/$readableId/edit': typeof AuthenticatedAppAuthProvidersConnectionsReadableIdEditRoute;
  '/_authenticated/_app/collections/$collectionId/connect-source/': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceIndexRoute;
  '/_authenticated/_app/collections/$collectionId/connect-source/$source/auth': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceAuthRoute;
  '/_authenticated/_app/collections/$collectionId/connect-source/$source/config': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceConfigRoute;
  '/_authenticated/_app/collections/$collectionId/connect-source/$source/sync': typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceSyncRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/onboarding'
    | '/api-keys'
    | '/auth-providers'
    | '/api-keys/create'
    | '/collections/$collectionId'
    | '/collections/'
    | '/auth-providers/$shortName/connect'
    | '/collections/$collectionId/connect-source'
    | '/auth-providers/connections/$readableId/delete'
    | '/auth-providers/connections/$readableId/edit'
    | '/collections/$collectionId/connect-source/'
    | '/collections/$collectionId/connect-source/$source/auth'
    | '/collections/$collectionId/connect-source/$source/config'
    | '/collections/$collectionId/connect-source/$source/sync';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/onboarding'
    | '/api-keys'
    | '/auth-providers'
    | '/api-keys/create'
    | '/collections/$collectionId'
    | '/collections'
    | '/auth-providers/$shortName/connect'
    | '/auth-providers/connections/$readableId/delete'
    | '/auth-providers/connections/$readableId/edit'
    | '/collections/$collectionId/connect-source'
    | '/collections/$collectionId/connect-source/$source/auth'
    | '/collections/$collectionId/connect-source/$source/config'
    | '/collections/$collectionId/connect-source/$source/sync';
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/login'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app/api-keys'
    | '/_authenticated/_app/auth-providers'
    | '/_authenticated/_app/'
    | '/_authenticated/_app/api-keys/create'
    | '/_authenticated/_app/collections/$collectionId'
    | '/_authenticated/_app/collections/'
    | '/_authenticated/_app/auth-providers/$shortName/connect'
    | '/_authenticated/_app/collections/$collectionId/connect-source'
    | '/_authenticated/_app/auth-providers/connections/$readableId/delete'
    | '/_authenticated/_app/auth-providers/connections/$readableId/edit'
    | '/_authenticated/_app/collections/$collectionId/connect-source/'
    | '/_authenticated/_app/collections/$collectionId/connect-source/$source/auth'
    | '/_authenticated/_app/collections/$collectionId/connect-source/$source/config'
    | '/_authenticated/_app/collections/$collectionId/connect-source/$source/sync';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  CallbackRoute: typeof CallbackRoute;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/callback': {
      id: '/callback';
      path: '/callback';
      fullPath: '/callback';
      preLoaderRoute: typeof CallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding';
      path: '/onboarding';
      fullPath: '/onboarding';
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/_app': {
      id: '/_authenticated/_app';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport;
      parentRoute: typeof AuthenticatedAppRouteRoute;
    };
    '/_authenticated/_app/auth-providers': {
      id: '/_authenticated/_app/auth-providers';
      path: '/auth-providers';
      fullPath: '/auth-providers';
      preLoaderRoute: typeof AuthenticatedAppAuthProvidersRouteImport;
      parentRoute: typeof AuthenticatedAppRouteRoute;
    };
    '/_authenticated/_app/api-keys': {
      id: '/_authenticated/_app/api-keys';
      path: '/api-keys';
      fullPath: '/api-keys';
      preLoaderRoute: typeof AuthenticatedAppApiKeysRouteImport;
      parentRoute: typeof AuthenticatedAppRouteRoute;
    };
    '/_authenticated/_app/collections/': {
      id: '/_authenticated/_app/collections/';
      path: '/collections';
      fullPath: '/collections/';
      preLoaderRoute: typeof AuthenticatedAppCollectionsIndexRouteImport;
      parentRoute: typeof AuthenticatedAppRouteRoute;
    };
    '/_authenticated/_app/collections/$collectionId': {
      id: '/_authenticated/_app/collections/$collectionId';
      path: '/collections/$collectionId';
      fullPath: '/collections/$collectionId';
      preLoaderRoute: typeof AuthenticatedAppCollectionsCollectionIdRouteImport;
      parentRoute: typeof AuthenticatedAppRouteRoute;
    };
    '/_authenticated/_app/api-keys/create': {
      id: '/_authenticated/_app/api-keys/create';
      path: '/create';
      fullPath: '/api-keys/create';
      preLoaderRoute: typeof AuthenticatedAppApiKeysCreateRouteImport;
      parentRoute: typeof AuthenticatedAppApiKeysRoute;
    };
    '/_authenticated/_app/collections/$collectionId/connect-source': {
      id: '/_authenticated/_app/collections/$collectionId/connect-source';
      path: '/connect-source';
      fullPath: '/collections/$collectionId/connect-source';
      preLoaderRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceRouteImport;
      parentRoute: typeof AuthenticatedAppCollectionsCollectionIdRoute;
    };
    '/_authenticated/_app/auth-providers/$shortName/connect': {
      id: '/_authenticated/_app/auth-providers/$shortName/connect';
      path: '/$shortName/connect';
      fullPath: '/auth-providers/$shortName/connect';
      preLoaderRoute: typeof AuthenticatedAppAuthProvidersShortNameConnectRouteImport;
      parentRoute: typeof AuthenticatedAppAuthProvidersRoute;
    };
    '/_authenticated/_app/collections/$collectionId/connect-source/': {
      id: '/_authenticated/_app/collections/$collectionId/connect-source/';
      path: '/';
      fullPath: '/collections/$collectionId/connect-source/';
      preLoaderRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceIndexRouteImport;
      parentRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceRoute;
    };
    '/_authenticated/_app/auth-providers/connections/$readableId/edit': {
      id: '/_authenticated/_app/auth-providers/connections/$readableId/edit';
      path: '/connections/$readableId/edit';
      fullPath: '/auth-providers/connections/$readableId/edit';
      preLoaderRoute: typeof AuthenticatedAppAuthProvidersConnectionsReadableIdEditRouteImport;
      parentRoute: typeof AuthenticatedAppAuthProvidersRoute;
    };
    '/_authenticated/_app/auth-providers/connections/$readableId/delete': {
      id: '/_authenticated/_app/auth-providers/connections/$readableId/delete';
      path: '/connections/$readableId/delete';
      fullPath: '/auth-providers/connections/$readableId/delete';
      preLoaderRoute: typeof AuthenticatedAppAuthProvidersConnectionsReadableIdDeleteRouteImport;
      parentRoute: typeof AuthenticatedAppAuthProvidersRoute;
    };
    '/_authenticated/_app/collections/$collectionId/connect-source/$source/sync': {
      id: '/_authenticated/_app/collections/$collectionId/connect-source/$source/sync';
      path: '/$source/sync';
      fullPath: '/collections/$collectionId/connect-source/$source/sync';
      preLoaderRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceSyncRouteImport;
      parentRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceRoute;
    };
    '/_authenticated/_app/collections/$collectionId/connect-source/$source/config': {
      id: '/_authenticated/_app/collections/$collectionId/connect-source/$source/config';
      path: '/$source/config';
      fullPath: '/collections/$collectionId/connect-source/$source/config';
      preLoaderRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceConfigRouteImport;
      parentRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceRoute;
    };
    '/_authenticated/_app/collections/$collectionId/connect-source/$source/auth': {
      id: '/_authenticated/_app/collections/$collectionId/connect-source/$source/auth';
      path: '/$source/auth';
      fullPath: '/collections/$collectionId/connect-source/$source/auth';
      preLoaderRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceAuthRouteImport;
      parentRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceRoute;
    };
  }
}

interface AuthenticatedAppApiKeysRouteChildren {
  AuthenticatedAppApiKeysCreateRoute: typeof AuthenticatedAppApiKeysCreateRoute;
}

const AuthenticatedAppApiKeysRouteChildren: AuthenticatedAppApiKeysRouteChildren =
  {
    AuthenticatedAppApiKeysCreateRoute: AuthenticatedAppApiKeysCreateRoute,
  };

const AuthenticatedAppApiKeysRouteWithChildren =
  AuthenticatedAppApiKeysRoute._addFileChildren(
    AuthenticatedAppApiKeysRouteChildren,
  );

interface AuthenticatedAppAuthProvidersRouteChildren {
  AuthenticatedAppAuthProvidersShortNameConnectRoute: typeof AuthenticatedAppAuthProvidersShortNameConnectRoute;
  AuthenticatedAppAuthProvidersConnectionsReadableIdDeleteRoute: typeof AuthenticatedAppAuthProvidersConnectionsReadableIdDeleteRoute;
  AuthenticatedAppAuthProvidersConnectionsReadableIdEditRoute: typeof AuthenticatedAppAuthProvidersConnectionsReadableIdEditRoute;
}

const AuthenticatedAppAuthProvidersRouteChildren: AuthenticatedAppAuthProvidersRouteChildren =
  {
    AuthenticatedAppAuthProvidersShortNameConnectRoute:
      AuthenticatedAppAuthProvidersShortNameConnectRoute,
    AuthenticatedAppAuthProvidersConnectionsReadableIdDeleteRoute:
      AuthenticatedAppAuthProvidersConnectionsReadableIdDeleteRoute,
    AuthenticatedAppAuthProvidersConnectionsReadableIdEditRoute:
      AuthenticatedAppAuthProvidersConnectionsReadableIdEditRoute,
  };

const AuthenticatedAppAuthProvidersRouteWithChildren =
  AuthenticatedAppAuthProvidersRoute._addFileChildren(
    AuthenticatedAppAuthProvidersRouteChildren,
  );

interface AuthenticatedAppCollectionsCollectionIdConnectSourceRouteChildren {
  AuthenticatedAppCollectionsCollectionIdConnectSourceIndexRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceIndexRoute;
  AuthenticatedAppCollectionsCollectionIdConnectSourceSourceAuthRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceAuthRoute;
  AuthenticatedAppCollectionsCollectionIdConnectSourceSourceConfigRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceConfigRoute;
  AuthenticatedAppCollectionsCollectionIdConnectSourceSourceSyncRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceSourceSyncRoute;
}

const AuthenticatedAppCollectionsCollectionIdConnectSourceRouteChildren: AuthenticatedAppCollectionsCollectionIdConnectSourceRouteChildren =
  {
    AuthenticatedAppCollectionsCollectionIdConnectSourceIndexRoute:
      AuthenticatedAppCollectionsCollectionIdConnectSourceIndexRoute,
    AuthenticatedAppCollectionsCollectionIdConnectSourceSourceAuthRoute:
      AuthenticatedAppCollectionsCollectionIdConnectSourceSourceAuthRoute,
    AuthenticatedAppCollectionsCollectionIdConnectSourceSourceConfigRoute:
      AuthenticatedAppCollectionsCollectionIdConnectSourceSourceConfigRoute,
    AuthenticatedAppCollectionsCollectionIdConnectSourceSourceSyncRoute:
      AuthenticatedAppCollectionsCollectionIdConnectSourceSourceSyncRoute,
  };

const AuthenticatedAppCollectionsCollectionIdConnectSourceRouteWithChildren =
  AuthenticatedAppCollectionsCollectionIdConnectSourceRoute._addFileChildren(
    AuthenticatedAppCollectionsCollectionIdConnectSourceRouteChildren,
  );

interface AuthenticatedAppCollectionsCollectionIdRouteChildren {
  AuthenticatedAppCollectionsCollectionIdConnectSourceRoute: typeof AuthenticatedAppCollectionsCollectionIdConnectSourceRouteWithChildren;
}

const AuthenticatedAppCollectionsCollectionIdRouteChildren: AuthenticatedAppCollectionsCollectionIdRouteChildren =
  {
    AuthenticatedAppCollectionsCollectionIdConnectSourceRoute:
      AuthenticatedAppCollectionsCollectionIdConnectSourceRouteWithChildren,
  };

const AuthenticatedAppCollectionsCollectionIdRouteWithChildren =
  AuthenticatedAppCollectionsCollectionIdRoute._addFileChildren(
    AuthenticatedAppCollectionsCollectionIdRouteChildren,
  );

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppApiKeysRoute: typeof AuthenticatedAppApiKeysRouteWithChildren;
  AuthenticatedAppAuthProvidersRoute: typeof AuthenticatedAppAuthProvidersRouteWithChildren;
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute;
  AuthenticatedAppCollectionsCollectionIdRoute: typeof AuthenticatedAppCollectionsCollectionIdRouteWithChildren;
  AuthenticatedAppCollectionsIndexRoute: typeof AuthenticatedAppCollectionsIndexRoute;
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppApiKeysRoute: AuthenticatedAppApiKeysRouteWithChildren,
  AuthenticatedAppAuthProvidersRoute:
    AuthenticatedAppAuthProvidersRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCollectionsCollectionIdRoute:
    AuthenticatedAppCollectionsCollectionIdRouteWithChildren,
  AuthenticatedAppCollectionsIndexRoute: AuthenticatedAppCollectionsIndexRoute,
};

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  );

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren;
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
