name: User Onboarding Test

on:
  pull_request_target: # Need access to secrets
    branches: [main]
  push:
    branches:
      - feat/user_onboarding_test_in_CI

jobs:
  test-onboarding:
    runs-on: ubuntu-latest

    steps:
      - name: Verify prerequisites
        run: |
          echo "Docker version:"
          docker --version
          echo "Docker Compose version:"
          docker compose version

      - name: Clone repository
        run: |
          git clone https://github.com/airweave-ai/airweave.git
          cd airweave

      - name: Run start script
        working-directory: ./airweave
        run: |
          chmod +x start.sh
          { echo "y"; echo "${{ secrets.OPENAI_API_KEY }}"; } | ./start.sh

      - name: Run basic health checks
        working-directory: ./airweave
        env:
          AIRWEAVE_TEST_ENV: onboarding
        run: |
          docker exec airweave-backend-1 pytest tests/e2e/smoke/test_basic_health.py -v
