name: Public API Test

on:
  pull_request_target: # Need access to secrets
    branches: [main]
  push:
    branches: [main]

jobs:
  test-public-api:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Verify prerequisites
        run: |
          echo "Docker version:"
          docker --version
          echo "Docker Compose version:"
          docker compose version

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest

      - name: Build test images locally
        run: |
          echo "Building backend image for testing..."
          docker build -t test-backend:latest ./backend
          echo "Building frontend image for testing..."
          docker build -t test-frontend:latest ./frontend

      - name: Run Public API Test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
          # Required test environment variables
          TEST_NOTION_TOKEN: ${{ secrets.TEST_NOTION_TOKEN }}
          TEST_GOOGLE_CLIENT_ID: ${{ secrets.TEST_GOOGLE_CLIENT_ID }}
          TEST_GOOGLE_CLIENT_SECRET: ${{ secrets.TEST_GOOGLE_CLIENT_SECRET }}
          TEST_AUTH_PROVIDER_NAME: composio
          TEST_COMPOSIO_API_KEY: ${{ secrets.TEST_COMPOSIO_API_KEY }}
          TEST_COMPOSIO_AUTH_CONFIG_ID: ${{ secrets.TEST_COMPOSIO_AUTH_CONFIG_ID }}
          TEST_COMPOSIO_ACCOUNT_ID: ${{ secrets.TEST_COMPOSIO_ACCOUNT_ID }}
          TEST_PIPEDREAM_CLIENT_ID: ${{ secrets.TEST_PIPEDREAM_CLIENT_ID }}
          TEST_PIPEDREAM_CLIENT_SECRET: ${{ secrets.TEST_PIPEDREAM_CLIENT_SECRET }}
          TEST_PIPEDREAM_PROJECT_ID: ${{ secrets.TEST_PIPEDREAM_PROJECT_ID }}
          TEST_PIPEDREAM_ACCOUNT_ID: ${{ secrets.TEST_PIPEDREAM_ACCOUNT_ID }}
          TEST_PIPEDREAM_EXTERNAL_USER_ID: ${{ secrets.TEST_PIPEDREAM_EXTERNAL_USER_ID }}
          # Override images to use locally built test images
          BACKEND_IMAGE: test-backend:latest
          FRONTEND_IMAGE: test-frontend:latest
        run: |
          cd backend
          python tests/e2e/smoke/test_public_api.py --env local

      - name: Cleanup Docker containers
        if: always()
        run: |
          echo "Cleaning up Docker containers..."
          docker compose down -v || true
          docker system prune -f || true
